import { MonthName, NetType } from "../types";

export const ALL_MONTHS: MonthName[] = [
  "জানুয়ারি",
  "ফেব্রুয়ারি",
  "মার্চ",
  "এপ্রিল",
  "মে",
  "জুন",
  "জুলাই",
  "আগস্ট",
  "সেপ্টেম্বর",
  "অক্টোবর",
  "নভেম্বর",
  "ডিসেম্বর",
];

export const NET_BILL_LINKS: Record<MonthName, string> = {
  "জানুয়ারি": "",
  "ফেব্রুয়ারি": "",
  "মার্চ": "",
  "এপ্রিল": "https://docs.google.com/spreadsheets/d/1JzUL1DOA_ubXONu9PhpCfo9oKeFj__o4oCGeeksV-pA/export?format=xlsx",
  "মে": "https://docs.google.com/spreadsheets/d/1nSM8fZUwHxUSZQc88u8Oaquch21226fYaC9n85NV3G0/export?format=xlsx",
  "জুন": "https://docs.google.com/spreadsheets/d/1cPxErMlxd24-YJPN6mBmA-3xPUjG_Ql3lMXEL8dFPzY/export?format=xlsx",
  "জুলাই": "https://docs.google.com/spreadsheets/d/1LWGmlA0yJwh6v1hQhpx4RrFeFBb_zW51D3GPehme-7s/export?format=xlsx",
  "আগস্ট": "https://docs.google.com/spreadsheets/d/1gZoIiCAYhUZW5nSQCUb6OoNDiNY-087JafIQGr0JaZA/export?format=xlsx",
  "সেপ্টেম্বর": "",
  "অক্টোবর": "",
  "নভেম্বর": "",
  "ডিসেম্বর": "",
};

export const DIS_BILL_LINKS: Record<MonthName, string> = {
  "জানুয়ারি": "",
  "ফেব্রুয়ারি": "",
  "মার্চ": "",
  "এপ্রিল": "https://docs.google.com/spreadsheets/d/1FjkMU78ge41qPdHa40byxscAo7zJHMj-uB6M1jKGtQM/export?format=xlsx",
  "মে": "https://docs.google.com/spreadsheets/d/1ai1RicItkQIl4_hpOhpP-olKc5FZLLrwLSKbYVFaS-M/export?format=xlsx",
  "জুন": "https://docs.google.com/spreadsheets/d/186olqasPT2CV0Feqs4OUOsdkbWSsA6is6E-faFNVqxI/export?format=xlsx",
  "জুলাই": "https://docs.google.com/spreadsheets/d/1Kzz2ac6SbeJgUyanm8YRVHKmMD3Cux-PfOSIsvurzAk/export?format=xlsx",
  "আগস্ট": "https://docs.google.com/spreadsheets/d/1h8v6TiQJeberx9R6VGTcQu7t6LiudOKrBS9WVqA2cZ0/export?format=xlsx",
  "সেপ্টেম্বর": "",
  "অক্টোবর": "",
  "নভেম্বর": "",
  "ডিসেম্বর": "",
};

export const NET_CONNECTION_LINKS: Record<MonthName, string> = {
  "জানুয়ারি": "",
  "ফেব্রুয়ারি": "",
  "মার্চ": "",
  "এপ্রিল": "",
  "মে": "https://docs.google.com/spreadsheets/d/16bT82iDAlejCN86k2PXGzuDdojeLLKgICFVKybNIWJc/export?format=xlsx",
  "জুন": "https://docs.google.com/spreadsheets/d/1MzoMhmIY3PGwIzzJ3Dif7FyNs_sHDXCYAu9oS7SKMtk/export?format=xlsx",
  "জুলাই": "https://docs.google.com/spreadsheets/d/1eWAu9sMK8vrDlV3Ue35jYY6rfNVM0EOE43ecdZtY0yc/export?format=xlsx",
  "আগস্ট": "https://docs.google.com/spreadsheets/d/144Km2kNlKpSdyQh9O1Q7BaIDf7bwOTGubTazHWMGPL0/export?format=xlsx",
  "সেপ্টেম্বর": "",
  "অক্টোবর": "",
  "নভেম্বর": "",
  "ডিসেম্বর": "",
};

export const DUE_BILL_LINKS: Record<MonthName, string> = {
  "জানুয়ারি": "",
  "ফেব্রুয়ারি": "",
  "মার্চ": "",
  "এপ্রিল": "",
  "মে": "",
  "জুন": "",
  "জুলাই": "https://docs.google.com/spreadsheets/d/1AWUhQdWBluPN3kGhG0jsLo224Qc0hst7DvM0PYwFVak/export?format=xlsx",
  "আগস্ট": "",
  "সেপ্টেম্বর": "",
  "অক্টোবর": "",
  "নভেম্বর": "",
  "ডিসেম্বর": "",
};

export function getLinksForNetType(type: NetType): Record<MonthName, string> {
  switch (type) {
    case "নেট বিল":
      return NET_BILL_LINKS;
    case "ডিস বিল":
      return DIS_BILL_LINKS;
    case "নেট সংযোগ":
      return NET_CONNECTION_LINKS;
    case "বকেয়া বিল":
      return DUE_BILL_LINKS;
    default:
      return NET_BILL_LINKS;
  }
}

export const TRANSLATIONS = {
  bn: {
    appTitle: "বিল ম্যানেজার",
    proBadge: "প্রো",
    tagline: "স্মার্ট বিল ব্যবস্থাপনা · সহজ · দ্রুত · নির্ভুল",
    dashboard: "ড্যাশবোর্ড",
    allBills: "সকল বিল",
    paidBills: "পরিশোধিত",
    dueBills: "বকেয়া বিল",
    totalBills: "সর্বমোট বিল",
    partialBills: "আংশিক",
    searchPlaceholder: "🔍 নাম, মোবাইল, আইডি বা ঠিকানা দিয়ে খুঁজুন...",
    noData: "কোন তথ্য পাওয়া যায়নি",
    noLink: "এই মাসের জন্য কোনো অনলাইন শিট লিংক নেই",
    offlineMode: "অফলাইন মোড",
    refreshing: "রিফ্রেশ হচ্ছে...",
    copySuccess: "ক্লিপবোর্ডে কপি হয়েছে!",
    dataLoaded: "ডেটা সফলভাবে লোড হয়েছে",
    cachedDataLoaded: "ক্যাশ থেকে ডেটা লোড হয়েছে",
    recentActivity: "সাম্প্রতিক কার্যক্রম",
    transactions: "টি রেকর্ড",
    noTransactions: "কোনো লেনদেন রেকর্ড নেই",
    dailyTrend: "গত ৭ দিনের বিল ট্রেন্ড",
    dailyAnalysis: "দৈনিক সংগ্রহ বিশ্লেষণ",
    paidVsDue: "পরিশোধিত বনাম বকেয়া",
    collectionStatus: "আদায় অবস্থা",
    monthlyIncome: "মাসভিত্তিক আয় (নেট বিল + ডিস বিল)",
    monthlySub: "১২ মাসের মোট আয় বিশ্লেষণ",
    backToDashboard: "◀ ড্যাশবোর্ডে ফিরুন",
    billDetails: "বিলের বিস্তারিত বিবরণ",
    name: "গ্রাহকের নাম",
    id: "কাস্টমার আইডি",
    mobile: "মোবাইল নম্বর",
    amount: "পরিশোধিত টাকা",
    dueAmount: "বকেয়া টাকা",
    totalAmount: "সর্বমোট টাকা",
    date: "তারিখ",
    address: "ঠিকানা",
    status: "স্ট্যাটাস",
    copy: "কপি",
    close: "বন্ধ করুন",
    sendSms: "বকেয়ার এসএমএস তৈরি করুন",
    smsCopied: "বকেয়া এসএমএস কপি হয়েছে!",
    exportExcel: "এক্সেল এক্সপোর্ট",
    importFile: "ফাইল আপলোড",
    addRecord: "নতুন এন্ট্রি",
    developer: "ডেভেলপার",
    collectionRate: "আদায় হার",
    dueRate: "বকেয়া হার",
    printReceipt: "রসিদ প্রিন্ট",
  },
  en: {
    appTitle: "Bill Manager",
    proBadge: "PRO",
    tagline: "Smart Bill Management · Fast · Accurate · Reliable",
    dashboard: "Dashboard",
    allBills: "All Bills",
    paidBills: "Paid Bills",
    dueBills: "Due Bills",
    totalBills: "Total Bills",
    partialBills: "Partial",
    searchPlaceholder: "🔍 Search by name, mobile, ID or address...",
    noData: "No data found",
    noLink: "No online sheet link configured for this month",
    offlineMode: "Offline Mode",
    refreshing: "Refreshing data...",
    copySuccess: "Copied to clipboard!",
    dataLoaded: "Data loaded successfully",
    cachedDataLoaded: "Loaded from offline cache",
    recentActivity: "Recent Activity",
    transactions: "records",
    noTransactions: "No transaction records",
    dailyTrend: "Last 7 Days Trend",
    dailyAnalysis: "Daily collection analytics",
    paidVsDue: "Paid vs Due",
    collectionStatus: "Collection Overview",
    monthlyIncome: "Monthly Income (Net + Dish)",
    monthlySub: "12-month revenue analytics",
    backToDashboard: "◀ Back to Dashboard",
    billDetails: "Bill Details",
    name: "Customer Name",
    id: "Customer ID",
    mobile: "Mobile Number",
    amount: "Paid Amount",
    dueAmount: "Due Amount",
    totalAmount: "Total Amount",
    date: "Date",
    address: "Address",
    status: "Status",
    copy: "Copy",
    close: "Close",
    sendSms: "Generate Due SMS",
    smsCopied: "Due reminder SMS copied!",
    exportExcel: "Export Excel",
    importFile: "Upload File",
    addRecord: "New Entry",
    developer: "Developer",
    collectionRate: "Collection Rate",
    dueRate: "Due Rate",
    printReceipt: "Print Receipt",
  },
};
